### ISSUE TITLE
3.3.1 increases MSRV to 1.56.0

### ISSUE THREAD

**Issue by link2xt** [tiby312/tagger#26]
Please revert upgrade to Rust 2021 edition. It unnecessarily bumps MSRV to 1.56.0, which has been released only recently. Especially since you don't use anything from the Rust 2021 edition and 4aae7a8cab65a9c340a0c9c8d24faf32d5a7558c can be simply reverted.

Combined with #25, I think the "correct" way is to revert 4aae7a8cab65a9c340a0c9c8d24faf32d5a7558c, yank 3.3.0 and 3.3.1, and release a 4.0.0.

cc @astraw

**Comment by link2xt** [comment]
I just recently upgraded to 3.3.0 by upgrading to the new `Result` API, and then a new version arrived that breaks our CI again: https://github.com/deltachat/deltachat-core-rust/pull/2893
Unlike previous case, we can't simply adapt to the new version because we support Rust 1.51.0.

**Comment by tiby312** [comment]
@link2xt I reverted it back to edition 2018 sorry about that!

**Comment by link2xt** [comment]
Thanks, updated to 4.0.1 with dependabot and it works!
